const styles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    backgroundColor: "#1a1a1a",
    color: "white",
    fontFamily: "Arial, sans-serif",
  },
  background: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    background: "linear-gradient(to bottom right, #1a2a6c, #b21f1f, #fdbb2d)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: "20px",
  },
  exitButton: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    color: "white",
    border: "none",
    padding: "8px 15px",
    borderRadius: "20px",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  scoreText: {
    fontSize: "24px",
    fontWeight: "bold",
  },
  timeText: {
    fontSize: "24px",
    fontWeight: "bold",
  },
  card: {
    width: "200px",
    height: "200px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "20px",
    margin: "20px 0",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  cardText: {
    fontSize: "48px",
    fontWeight: "bold",
  },
  buttonContainer: {
    display: "flex",
    flexWrap: "wrap" as const,
    justifyContent: "center",
    padding: "20px",
  },
  colorButton: {
    width: "60px",
    height: "60px",
    margin: "10px",
    borderRadius: "30px",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  title: {
    fontSize: "32px",
    fontWeight: "bold",
    marginBottom: "40px",
    textAlign: "center" as const,
  },
  startButton: {
    backgroundColor: "rgba(255,255,255,0.2)",
    color: "white",
    border: "none",
    padding: "15px",
    borderRadius: "10px",
    width: "200px",
    marginVertical: "10px",
    fontSize: "18px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  highScoreContainer: {
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: "15px",
    borderRadius: "10px",
    marginBottom: "20px",
    width: "80%",
    maxWidth: "300px",
    textAlign: "center" as const,
  },
  highScoreTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    marginBottom: "10px",
  },
  highScoreText: {
    fontSize: "16px",
    margin: "2px 0",
  },
  levelSelector: {
    display: "flex",
    alignItems: "center",
    marginBottom: "20px",
  },
  levelText: {
    fontSize: "24px",
    margin: "0 20px",
  },
  levelButton: {
    color: "white",
    backgroundColor: "transparent",
    border: "none",
    fontSize: "32px",
    margin: "0 10px",
    width: "40px",
    cursor: "pointer",
  },
}

export default styles

